[workspace]
authors = ["nmarticorena <nicolas.marticorena.vidal@gmail.com>"]
channels = ["conda-forge"]
name = "GMR"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[pypi-options]
no-build-isolation = true

[dependencies]
python = "==3.11"
libstdcxx-ng = ">=15.2.0,<16"
numpy = "<2"
scipy = ">=1.14"
setuptools = ">=82.0.0,<83"

[pypi-dependencies]
general-motion-retargeting = {path = ".", editable = true}
